#!/bin/bash

ManageProtocol() {
        LimeConfig="lime-community";
        local Protocol="$1";
        local Include="$2";
        if uci show $LimeConfig | grep -q "$Protocol"; then
                if [ "$Include" = false ]; then
                        uci del_list $LimeConfig.network.protocols="$Protocol";
                fi;
        else
                if [ "$Include" = true ]; then
                        uci add_list $LimeConfig.network.protocols="$Protocol";
                fi;
        fi;
        uci commit $LimeConfig;
}

NodeProfileConf(){
        SelectedNetworkProfile=$(uci get fmesh.core.network_profile)
        if [[ $SelectedNetworkProfile == *"bat"* ]]; then
                ManageProtocol "batadv:%N1" true
        else
                ManageProtocol "batadv:%N1" false
        fi;
        if [[ $SelectedNetworkProfile == *"bmx"* ]]; then
                uci set luci-bmx7.luci.ignore="0"
                ManageProtocol "bmx7:18" true
        else
                uci set luci-bmx7.luci.ignore="1"
                ManageProtocol "bmx7:18" false
        fi;
        uci commit luci-bmx7;
        lime-config && lime-apply
        /etc/init.d/rpcd restart
}

NodeIndexConf(){
        Filepath="/root/old_factory"
        dd if=/dev/mtd2 of=$Filepath
        DefaultMAC=$( dd if=$Filepath bs=1 skip=$((0xe000)) count=6 | xxd -p );
        DefaultMAC=$(echo "$DefaultMAC" | xargs);
        NodeId="$(uci get fmesh.core.node_id_one)$(uci get fmesh.core.node_id_two)"
        NewMACPart=$(echo "$NodeId" | awk '{print tolower($0)}');
        InitialPartLength=$((${#DefaultMAC}-${#NewMACPart}))
        if [ "${DefaultMAC:InitialPartLength}" = "$NewMACPart" ];then
                echo "[FAU2OS-utils]: Node Id didn't changed. Nothing to do.." > /dev/kmsg
                return
        fi;
        InitialPart=${DefaultMAC:0:InitialPartLength}
        NewMAC="$InitialPart$NewMACPart"
        echo "[FAU2OS-utils]: Rewriting $DefaultMAC --> $NewMAC" > /dev/kmsg

        LimeReconfScript="/etc/uci-defaults/lime-reconf.sh"
cat << EOF > "$LimeReconfScript"
#!/bin/bash
uci set network.lan_eth0_1_dev.macaddr="$(cat /sys/class/ieee80211/phy0/macaddress)"
uci set network.wan_eth0_2_dev.macaddr="$(cat /sys/class/ieee80211/phy1/macaddress)"
uci commit network
lime-config && lime-apply
rm $Filepath
/etc/init.d/network restart
EOF
        chmod +x "$LimeReconfScript"

        NewMACBinary=$(echo -n $NewMAC | sed 's/\(..\)/\\x\1/g')
        echo -ne $NewMACBinary | dd of=$Filepath bs=1 seek=$((0xe000)) conv=notrunc
        insmod mtd-rw.ko i_want_a_brick=1
        mtd -r write $Filepath factory
}

if [ "$1" = "index" ];then
        NodeIndexConf $2
elif [ "$1" = "profile" ]; then
        NodeProfileConf
else
        echo "you should specify the role. Usage: $0 index | profile"
fi;
